on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n csm17 -g csm17b61a-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n csm17 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n csm17 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n csm17 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: csm17.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t csm17.azurecr.io/cs:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push csm17.azurecr.io/cs:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_cs_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep csb854 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace csb854`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: csb854
        container-registry-url: csm17.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: csdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: csb854
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          csm17.azurecr.io/cs:${{ github.sha }}
        imagepullsecrets: |
          csdockerauth   
